target 'GitHubApp' do
#pod 'RongCloudIM/IMLib', '~> 2.8.3'
#pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'SDWebImage', '~> 4.0.0'
pod 'AFNetworking', '~> 3.0' 
pod 'MJRefresh', '~> 3.1.12'
#pod 'SPPageMenu'
#pod 'BmobSDK'
pod 'SDCycleScrollView'
#pod 'TZImagePickerController'
#pod 'SDAutoLayout'
pod 'IQKeyboardManager'
#pod 'LCActionSheet'
#pod 'Masonry'
#pod 'SAMKeychain'
#pod 'MJExtension'
#pod 'AMap2DMap'
#pod 'AMapSearch'
#pod 'AMapLocation'
pod 'HUPhotoBrowser', '~> 1.3.0'
#pod 'RATreeView'
#pod 'JSONModel'

# 主模块(必须)
#pod 'mob_sharesdk'
#
## UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#pod 'mob_sharesdk/ShareSDKUI'
#
## 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
#pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'      #微信sdk不带支付的命令）
# pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' //（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
end
